name: Rust Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        # toolchain: stable
        toolchain: 1.69.0
        override: true

    - name: Get the ref name
      id: get_ref_name
      run: |
        REF_NAME=$(echo "${{ github.ref }}" | sed -r 's/refs\/(heads|tags)\///')
        echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV

    - name: Install OpenSSL static libraries
      run: sudo apt-get install -y libssl-dev

    - name: Build
      run: OPENSSL_STATIC=1 cargo build --release
#      uses: actions-rs/cargo@v1
#      with:
#       command: build
#       args: --release

    - name: Display build size
      run: du -sh target/release/rust_socketio_cli

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: rust_socketio_cli
        path: target/release/rust_socketio_cli